name:                wai-saml2
version:             0.1.0.0
github:              "mbg/wai-saml2"
license:             MIT
author:              "Michael B. Gale"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright (c) Michael B. Gale"

category:            Security
synopsis:            "SAML2 assertion validation as WAI middleware"
description:         "A Haskell library which implements SAML2 assertion validation as WAI middleware"

default-extensions:
- OverloadedStrings
- MultiWayIf
- RecordWildCards
- FlexibleInstances

dependencies:
- base
- text
- bytestring
- base64-bytestring
- data-default-class
- http-types
- wai
- wai-extra
- vault
- cryptonite
- x509
- x509-store
- xml-conduit
- time
- mtl
- c14n

library:
    source-dirs: src
    ghc-options:
    - -W

